// Arquivo gerado automaticamente!
#ifndef SITES_H
#define SITES_H

const char* APLICACAO = "<style> .tela { display: none; } .ativa { display: block; } body { background-color: #191c1f; font-family: 'Segoe UI', A"
"rial, sans-serif; margin: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; } .caixa_me"
"nu { border: 1px solid #444; border-radius: 20px; max-width: 15rem; background-color: #a7a3a3; box-shadow: 0 15px 35px r"
"gba(255, 255, 255, 0.2); text-align: center; overflow: hidden; } .textoPrincipal { padding: 10px 0px; } .textoPrincipal "
"h1 { margin: 0; font-size: 3.2rem; color: #000000; letter-spacing: 4px; } .ConjuntoBotoes { display: flex; flex-directio"
"n: column; gap: 1.5rem; padding: 30px; align-items: center; } .botaoGeral { width: 12rem; padding: 15px 25px; font-size:"
" 2rem; font-weight: bold; color: white; background-color: #2a82bdc0; border: 3px outset; border-radius: 30px; cursor: po"
"inter; transition: all 0.5s ease; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.5); } .botaoGeral:hover { background-color: #4b1"
"d96; transform: translateY(-4px); box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2); } .botaoGeral:active { transform: translate"
"Y(5px); box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); } .gradeLuzes { display: grid; grid-template-columns: repeat(2, 1fr); "
"gap: 10px; padding: 20px; justify-items: center; } .botaoLampada { width: 80px; height: 80px; border-radius: 50%; border"
": 2px solid #ccc; background-color: #1b2631a4; color: white; font-size: 15px; font-weight: bold; cursor: pointer; transi"
"tion: all 0.3s ease; display: flex; flex-direction: column; align-items: center; justify-content: center; box-shadow: 0 "
"4px 6px rgba(0,0,0,0.3); } .botaoLampada.acesa { background-color: #f1c40f; color: #333; box-shadow: 0 0 15px #f1c40f; b"
"order-color: #d4ac0d; } .botaoVoltar { width: 10rem; font-size: 1.5rem; background-color: #003e6bc0; } .fundo_porta { pe"
"rspective: 1000px; width: 80px; height: 110px; background-color: #333; border: 3px solid #5d4037; position: relative; cu"
"rsor: pointer; border-radius: 5px; } .frente_porta { width: 89%; height: 100%; background-color: #8d6e63; border: 1px so"
"lid #4e342e; display: flex; align-items: center; justify-content: flex-end; padding-right: 8px; transition: transform 0."
"6s cubic-bezier(0.4, 0, 0.2, 1); transform-origin: left; z-index: 2; } .frente_porta::after { content: ''; width: 8px; h"
"eight: 8px; background-color: #ffd700; border-radius: 50%; box-shadow: 1px 1px 2px rgba(0,0,0,0.5); } .aberta .frente_po"
"rta { transform: rotateY(-100deg); } </style><script> function mudarTela(id) { document.querySelectorAll('.tela').forEac"
"h(t => t.classList.remove('ativa')); const proximaTela = document.getElementById(id); if(proximaTela) proximaTela.classL"
"ist.add('ativa'); } function enviarComando(url) { fetch(url).catch(err => console.log(\"Erro de rede\")); } function toggl"
"eLuz(id, botao) { botao.classList.toggle('acesa'); const estado = botao.classList.contains('acesa') ? 'on' : 'off'; envi"
"arComando(`/${id}/${estado}`); } function togglePorta(id, elemento) { elemento.classList.toggle('aberta'); const estado "
"= elemento.classList.contains('aberta') ? 'aberta' : 'fechada'; enviarComando(`/${id}/${estado}`); } function atualizarI"
"nterface() { fetch('/status?t=' + Date.now(), { cache: \"no-store\" }) .then(resposta => { if (!resposta.ok) throw new Err"
"or(\"Erro na rede\"); return resposta.json(); }) .then(dados => { const btnLuz1 = document.getElementById('btnLuz1'); if ("
"dados.luz1 === 'on') btnLuz1.classList.add('acesa'); else btnLuz1.classList.remove('acesa'); const btnLuz2 = document.ge"
"tElementById('btnLuz2'); if (dados.luz2 === 'on') btnLuz2.classList.add('acesa'); else btnLuz2.classList.remove('acesa')"
"; const btnLuz3 = document.getElementById('btnLuz3'); if (dados.luz3 === 'on') btnLuz3.classList.add('acesa'); else btnL"
"uz3.classList.remove('acesa'); const btnLuz4 = document.getElementById('btnLuz4'); if (dados.luz4 === 'on') btnLuz4.clas"
"sList.add('acesa'); else btnLuz4.classList.remove('acesa'); const btnPorta = document.getElementById('btnPorta'); if (da"
"dos.porta === 'aberta') btnPorta.classList.add('aberta'); else btnPorta.classList.remove('aberta'); }) .catch(erro => co"
"nsole.log(\"Falha ao sincronizar com o Pico:\", erro)) .finally(() => { setTimeout(atualizarInterface, 1500); }); } window"
".onload = atualizarInterface; </script><div id=\"tela_main\" class=\"tela ativa caixa_menu\"><div class=\"textoPrincipal\"><h1"
">MENU</h1></div><div class=\"ConjuntoBotoes\"><button class=\"botaoGeral\" onclick=\"mudarTela('tela_luzes')\"> LUZES </button"
"><!-- <button class=\"botaoGeral\" onclick=\"mudarTela('tela_portas')\"> PORTAS </button> --></div></div><div id=\"tela_luzes"
"\" class=\"tela\"><div class=\"caixa_menu\"><div class=\"textoPrincipal\"><h1>LUZES</h1></div><div class=\"gradeLuzes\"><button i"
"d=\"btnLuz1\" class=\"botaoGeral botaoLampada\" onclick=\"toggleLuz('luz1', this)\">LAMP 1</button><button id=\"btnLuz2\" class="
"\"botaoGeral botaoLampada\" onclick=\"toggleLuz('luz2', this)\">LAMP 2</button><button id=\"btnLuz3\" class=\"botaoGeral botaoL"
"ampada\" onclick=\"toggleLuz('luz3', this)\">LAMP 3</button><button id=\"btnLuz4\" class=\"botaoGeral botaoLampada\" onclick=\"t"
"oggleLuz('luz4', this)\">LAMP 4</button></div><div class=\"ConjuntoBotoes\"><button class=\"botaoGeral botaoVoltar\" onclick="
"\"mudarTela('tela_main')\"> VOLTAR </button></div></div></div><!-- <div id=\"tela_portas\" class=\"tela\"><div class=\"caixa_me"
"nu\"><div class=\"textoPrincipal\"><h1 style=\"font-size: 2.5rem;\">PORTAS</h1></div><div style=\"display:flex; flex-direction"
":column; align-items:center;\"><div id=\"btnPorta\" class=\"fundo_porta\" onclick=\"togglePorta('porta_sala', this)\"><div clas"
"s=\"frente_porta\"></div></div></div><div class=\"ConjuntoBotoes\"><button class=\"botaoGeral botaoVoltar\" onclick=\"mudarTela"
"('tela_main')\"> VOLTAR </button></div></div></div> -->";

#endif
